"""``_gateway_status`` must not report "unknown" from inside the gateway.

The 2026-09-12 debug report was generated by ``/debug`` inside a *running*
gateway, yet the dump's ``gateway:`` line said ``unknown`` — the runtime
snapshot shells out to systemd/launchd and raised inside that process. When
the process itself is the gateway (``_HERMES_GATEWAY=1``, set by
``gateway/run.py`` at import), the dump must say so instead of a meaningless
"unknown".
"""

import os
import sys
from unittest.mock import patch

import pytest


def test_gateway_status_reports_in_process_when_snapshot_raises(monkeypatch):
    from hermes_cli import dump

    def _boom():
        raise RuntimeError("systemctl unreachable from gateway process")

    monkeypatch.setenv("_HERMES_GATEWAY", "1")
    with patch(
        "hermes_cli.gateway.get_gateway_runtime_snapshot", side_effect=_boom
    ):
        status = dump._gateway_status()

    assert status.startswith("running (in-process")
    assert str(os.getpid()) in status


def test_gateway_status_keeps_unknown_outside_gateway_when_snapshot_raises(monkeypatch):
    from hermes_cli import dump

    def _boom():
        raise RuntimeError("no service manager on this host")

    monkeypatch.delenv("_HERMES_GATEWAY", raising=False)
    with patch(
        "hermes_cli.gateway.get_gateway_runtime_snapshot", side_effect=_boom
    ):
        status = dump._gateway_status()

    if sys.platform.startswith(("linux", "darwin")):
        assert status == "unknown"
    else:
        assert status == "N/A"


def test_gateway_status_still_prefers_snapshot_when_it_works(monkeypatch):
    """The marker is only a fallback — a working snapshot still wins."""
    from hermes_cli import dump
    from hermes_cli.gateway import GatewayRuntimeSnapshot

    monkeypatch.setenv("_HERMES_GATEWAY", "1")
    snapshot = GatewayRuntimeSnapshot(
        manager="systemd (user)", gateway_pids=(4242,)
    )
    with patch(
        "hermes_cli.gateway.get_gateway_runtime_snapshot", return_value=snapshot
    ):
        status = dump._gateway_status()

    assert "running" in status
    assert "4242" in status
